### ISSUE TITLE
Invalid pseudocolumn "$ivlen" on SQl Server 2016

### ISSUE THREAD

**Issue by bezik46** [NetSPI/Powershell-Modules#5]
running the query “SELECT name,credential_identity…” over a DAC connection
against SQL Server 2016 CU6

Msg 126, Level 15, State 1, Line 2
Invalid pseudocolumn "$ivlen".

**Comment by arantasa** [comment]
$ivlen is a PowerShell variable, it doesn't work in a plain SQL query.
