### ISSUE TITLE
valclass=28 and valnum=2 seems to NOT exists

### ISSUE THREAD

**Issue by bezik46** [NetSPI/Powershell-Modules#6]
DAC connection to either SQL 2012 or 2016

use master
select * from sys.sysobjvalues

There simply are NO valclass=28 entries

**Comment by arantasa** [comment]
valclass=28 entries are created if there are credentials (not SQL Server logins) on the server.

**Comment by bezik46** [comment]
Thank you, as simple as that, of course!
